[package]
name = "cricket-ffi"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = []
ffi = ["dep:uniffi", "cricket-protocol/ffi"]

[dependencies]
cricket-agent = { path = "../cricket-agent" }
cricket-protocol = { path = "../cricket-protocol" }
uniffi = { version = "0.28", optional = true }
